export const VIRAG = [
    {
    kep:"kepek/tulipan.png",
    nev:"Tulipán",
    elet:2,
    szine:"piros"
},
{
    kep:"kepek/napraforgo.jpg",
    nev:"Napraforgó",
    elet:2,
    szine:"sárga"
},
{
    kep:"kepek/Bazsarozsa.jpg",
    nev:"Bazsarózsa",
    elet:2,
    szine:"rózsaszín"
},
{
    kep:"kepek/jacint.jpg",
    nev:"Jácint",
    elet:2,
    szine:"lila"
},
{
    kep:"kepek/GYongyvirag.jpg",
    nev:"Gyöngyvirág",
    elet:2,
    szine:"fehér"
}
]

console.log(VIRAG)